from registers.models import RecurringExpense
from django.db.models import Sum


class RecurringExpenseRepository:
    """
    Repository for RecurringExpense model following SOLID principles.
    Handles data access and query optimization for recurring expenses.
    """

    def get_total_recurring_expenses_with_debit(self, user=None):
        """
        Calculate the total amount of recurring expenses that have generate_debit=True.

        Args:
            user: User instance (optional, filters by user if provided)

        Returns:
            Decimal: Total amount of active recurring expenses
        """
        queryset = RecurringExpense.objects.filter(generate_debit=True)
        if user:
            queryset = queryset.filter(user=user)
        return queryset.aggregate(total=Sum('total_amount'))['total'] or 0

    def get_total_inactive_recurring_expenses(self, user):
        """
        Calculate total amount of inactive recurring expenses (generate_debit=False).

        Args:
            user: User instance

        Returns:
            Decimal: Total amount of inactive recurring expenses
        """
        return (
            RecurringExpense.objects
            .filter(user=user, generate_debit=False)
            .aggregate(total=Sum('total_amount'))['total'] or 0
        )

    def get_total_all_recurring_expenses(self, user):
        """
        Calculate total amount of all recurring expenses (active + inactive).

        Args:
            user: User instance

        Returns:
            Decimal: Total amount of all recurring expenses
        """
        return (
            RecurringExpense.objects
            .filter(user=user)
            .aggregate(total=Sum('total_amount'))['total'] or 0
        )

    def get_active_recurring_expenses(self):
        """
        Get all active recurring expenses (generate_debit=True) with optimized query.

        Returns:
            QuerySet: Optimized queryset with related objects
        """
        return (
            RecurringExpense.objects
            .filter(generate_debit=True)
            .select_related('category', 'payment_method', 'user')
            .order_by('description')
        )

    def get_recurring_expenses_by_user(self, user):
        """
        Get recurring expenses for a specific user.

        Args:
            user: User instance

        Returns:
            QuerySet: User's recurring expenses with related objects
        """
        return (
            RecurringExpense.objects
            .filter(user=user, generate_debit=True)
            .select_related('category', 'payment_method')
            .order_by('description')
        )

    def get_recurring_expense_count(self):
        """
        Get count of active recurring expenses.

        Returns:
            int: Number of active recurring expenses
        """
        return RecurringExpense.objects.filter(generate_debit=True).count()

    def get_all_recurring_expenses_by_user(self, user):
        """
        Fetch all user's recurring expenses with optimized query including expense counts.

        Args:
            user: User instance

        Returns:
            QuerySet: All user's recurring expenses (active and inactive) with expense_count annotation
        """
        from django.db.models import Count
        return (
            RecurringExpense.objects
            .filter(user=user)
            .select_related('category', 'payment_method', 'user')
            .annotate(expense_count=Count('recurring_expenses'))
            .order_by('-generate_debit', '-total_amount', 'description')
        )

    def get_recurring_expense_by_id(self, recurring_expense_id):
        """
        Busca uma despesa fixa específica com relacionamentos.

        Args:
            recurring_expense_id: ID of the recurring expense

        Returns:
            RecurringExpense: Single recurring expense instance
        """
        return (
            RecurringExpense.objects
            .select_related('category', 'payment_method', 'user')
            .get(id=recurring_expense_id)
        )

    def get_expenses_by_recurring_expense(self, recurring_expense_id):
        """
        Busca todas as despesas geradas por uma despesa fixa.

        Args:
            recurring_expense_id: ID of the recurring expense

        Returns:
            QuerySet: Expenses generated by the recurring expense
        """
        from registers.models import Expense
        return (
            Expense.objects
            .filter(reccurring_expense_id=recurring_expense_id)
            .select_related('category', 'payment_method')
            .order_by('-date')
        )

    def toggle_generate_debit(self, recurring_expense_id):
        """
        Alterna o campo generate_debit (ativar/desativar).

        Args:
            recurring_expense_id: ID of the recurring expense

        Returns:
            RecurringExpense: Updated recurring expense instance
        """
        recurring_expense = RecurringExpense.objects.get(id=recurring_expense_id)
        recurring_expense.generate_debit = not recurring_expense.generate_debit
        recurring_expense.save()
        return recurring_expense