# Generated by Django 5.1.1 on 2025-03-29 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registers', '0006_paymentmethod_start_billing_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('billing_month', models.CharField(max_length=20)),
                ('billing_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.paymentmethod')),
            ],
            options={
                'ordering': ['billing_year', 'start_date'],
                'unique_together': {('payment_method', 'billing_month', 'billing_year')},
            },
        ),
    ]
