# Generated by Django 5.1.1 on 2025-08-10 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0006_paymentmethod_start_billing_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexpense',
            name='generate_debit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='reccurring_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='registers.recurringexpense'),
        ),
    ]
