# Generated by Django 5.1.1 on 2026-06-05 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0011_fix_categorybudgetestimate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
