# Generated by Django 5.1.1 on 2026-09-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0012_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
